### ISSUE TITLE
upload to S3 a zipped list of URLs to shuffle through

### ISSUE THREAD

**Issue by gserra-olx** [goadapp/goad#103]
I already did some hacks on this, but they have some limitations
 - please use the INI based configuration you find on my fork github.com/zeph/goad
 - push it as payload at lambda activation
 - the gzipped file list has to go into S3

p.s. another bad hack (that required a compilation before running the code) is here
 - github.com/zeph/goad/tree/single_huge_list

**Comment by andymac4182** [comment]
Could you use the environment variables support in lambda for this now? Would reduce delays since you wouldn't need to load any files.

**Comment by gserra-olx** [comment]
@andymac4182 could u elaborate a bit more? I'm not sure I fully get your proposal

my interpretation: u wish we upload the file to S3 and reference it back to the lambda function via an environment variable instead of posting a configuration payload?

**Comment by andymac4182** [comment]
My idea was just you could use the environment variables instead of a file at all. eg.
```
Url = "http://test.com/1","http://test.com/2"
```
or 
```
Url[0] = http://test.com/1
Url[1] = http://test.com/2
```

Using S3 incurs a small but still there delay in starting up the lambda. The environment variables are passed in from the start and easy to develop locally with.

**Comment by gserra-olx** [comment]
@andymac4182 the problem with that approach is that you are solving one single problem introducing a new way to interact with the tool, and a new feature will create another way, and the next one will have one more a smart idea to pass such parameter... I'm trying to settle on a standard... ab (apache benchmark) style CLI as a base for everybody, and anything else via INI files to drive further extensions of the tool

your idea is not bad, but if u need to provide a huge list of urls, what would u end up with? a huge set of environment variables? what's the limit on AWS API? what's the limit on bash (if there's a limit) ?

**Comment by zeph** [comment]
ok, we are not going to implement this... siege npm library shall be covering it

**Comment by jeff1985** [comment]
i'm searching for a similar setup. how can i use siege with goad?

**Comment by zeph** [comment]
@jeff1985 we are aiming to provide an abstract interface to plug in whatever AWS Lambda compatible executor u want... in the specific the idea is to get to the point of using the `npm siege` library and u simply have to initialise your local directory with such library and a list of URLs

we are not yet there... there are many things to be cleaned up first 
 - https://github.com/goadapp/goad/projects/1
