### ISSUE TITLE
create a pull request for HomeBrew Cask

### ISSUE THREAD

**Issue by gserra-olx** [goadapp/goad#104]
u can copy a snippet from:
 - https://github.com/zeph/goad/blob/master/Casks/goad.rb

we do have automated builds also in goadapp organization at github.com/goadapp/goad/releases

**Comment by cwaltken-edrans** [comment]
This is already done. We could safely delete the hombrew recipe from our local repository and close this now.

**Comment by zeph** [comment]
@cwaltken-edrans sure, please proceed

i'll close this
