### ISSUE TITLE
Client logs

### ISSUE THREAD

**Issue by jicowan** [goadapp/goad#106]
Does goad capture the client logs?  If the site throws a 4xx or 5xx, will it appear in the Lambda logs?

**Comment by zeph** [comment]
@jicowan no, I had a patch for it, logs go actually in the Amazon Cloudwatch infrastructure

would that work for u? do u need a count or see the actual output of the request?

**Comment by jicowan** [comment]
@zeph When you say the logs to go CloudWatch, you mean the Lambda execution logs or something else.  The Lambda execution logs only show a summary of the requests.  I'll see what I can glean from the ALB logs.

**Comment by zeph** [comment]
@jicowan lambda on AWS emits stdout and stderr and those are collected into cloudwatch

there is no logs/output information going back to the GOAD client running from ur laptop

**Comment by jicowan** [comment]
This is what is output to the Lambda logs: 
`
33215564596561755455681484319624999334596378036118224933
EVENTS	1489437428419	START RequestId: d396862e-082c-11e7-acf3-91257d9c9f2f Version: 1
	1489437428376
EVENTS	1489437443491	2017-03-13T20:37:08.383Z	d396862e-082c-11e7-acf3-91257d9c9f2f	Using a timeout of 15s
Using a reporting frequency of 2s
Will spawn 1 workers making 333 requests to http://blue-green-alb-1428113836.us-east-1.elb.amazonaws.com
Spawning workers…. done.
Waiting for results…

	1489437428384
EVENTS	1489437443491	2017-03-13T20:37:08.418Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
3.00% done (10 requests out of 333)
	1489437428418
EVENTS	1489437443491	2017-03-13T20:37:08.441Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
6.01% done (20 requests out of 333)
	1489437428441
EVENTS	1489437443491	2017-03-13T20:37:08.464Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
9.01% done (30 requests out of 333)
	1489437428464
EVENTS	1489437443491	2017-03-13T20:37:08.488Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
12.01% done (40 requests out of 333)
	1489437428488
EVENTS	1489437443491	2017-03-13T20:37:08.511Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
15.02% done (50 requests out of 333)
	1489437428511
EVENTS	1489437443491	2017-03-13T20:37:08.534Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
18.02% done (60 requests out of 333)
	1489437428534
EVENTS	1489437443491	2017-03-13T20:37:08.557Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
21.02% done (70 requests out of 333)
	1489437428557
EVENTS	1489437443491	2017-03-13T20:37:08.581Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
24.02% done (80 requests out of 333)
	1489437428581
EVENTS	1489437443491	2017-03-13T20:37:08.605Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
27.03% done (90 requests out of 333)
	1489437428605
EVENTS	1489437443491	2017-03-13T20:37:08.628Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
30.03% done (100 requests out of 333)
	1489437428628
EVENTS	1489437443491	2017-03-13T20:37:08.646Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
33.03% done (110 requests out of 333)
	1489437428646
EVENTS	1489437443491	2017-03-13T20:37:08.661Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
36.04% done (120 requests out of 333)
	1489437428661
EVENTS	1489437443491	2017-03-13T20:37:08.676Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
39.04% done (130 requests out of 333)
	1489437428676
EVENTS	1489437443491	2017-03-13T20:37:08.690Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
42.04% done (140 requests out of 333)
	1489437428691
EVENTS	1489437443491	2017-03-13T20:37:08.707Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
45.05% done (150 requests out of 333)
	1489437428707
EVENTS	1489437443491	2017-03-13T20:37:08.721Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
48.05% done (160 requests out of 333)
	1489437428721
EVENTS	1489437443491	2017-03-13T20:37:08.736Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
51.05% done (170 requests out of 333)
	1489437428736
EVENTS	1489437443491	2017-03-13T20:37:08.752Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
54.05% done (180 requests out of 333)
	1489437428752
EVENTS	1489437443491	2017-03-13T20:37:08.766Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
57.06% done (190 requests out of 333)
	1489437428766
EVENTS	1489437443491	2017-03-13T20:37:08.781Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
60.06% done (200 requests out of 333)
	1489437428781
EVENTS	1489437443491	2017-03-13T20:37:08.803Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
63.06% done (210 requests out of 333)
	1489437428803
EVENTS	1489437443491	2017-03-13T20:37:08.823Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
66.07% done (220 requests out of 333)
	1489437428823
EVENTS	1489437443491	2017-03-13T20:37:08.844Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
69.07% done (230 requests out of 333)
	1489437428844
EVENTS	1489437443491	2017-03-13T20:37:08.864Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
72.07% done (240 requests out of 333)
	1489437428864
EVENTS	1489437443491	2017-03-13T20:37:08.885Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
75.08% done (250 requests out of 333)
	1489437428885
EVENTS	1489437443491	2017-03-13T20:37:08.905Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
78.08% done (260 requests out of 333)
	1489437428905
EVENTS	1489437443491	2017-03-13T20:37:08.925Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
81.08% done (270 requests out of 333)
	1489437428926
EVENTS	1489437443491	2017-03-13T20:37:08.945Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
84.08% done (280 requests out of 333)
	1489437428945
EVENTS	1489437443491	2017-03-13T20:37:08.965Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
87.09% done (290 requests out of 333)
	1489437428965
EVENTS	1489437443491	2017-03-13T20:37:08.986Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
90.09% done (300 requests out of 333)
	1489437428986
EVENTS	1489437443491	2017-03-13T20:37:09.002Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
93.09% done (310 requests out of 333)
	1489437429002
EVENTS	1489437443491	2017-03-13T20:37:09.018Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
96.10% done (320 requests out of 333)
	1489437429018
EVENTS	1489437443491	2017-03-13T20:37:09.032Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
99.10% done (330 requests out of 333)
	1489437429032
EVENTS	1489437443491	2017-03-13T20:37:09.037Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
100.00% done (333 requests out of 333)
	1489437429037
EVENTS	1489437443491	2017-03-13T20:37:09.142Z	d396862e-082c-11e7-acf3-91257d9c9f2f	
Yay🎈  - 333 requests completed

	1489437429142
EVENTS	1489437443491	END RequestId: d396862e-082c-11e7-acf3-91257d9c9f2f
	1489437429147
EVENTS	1489437443491	REPORT RequestId: d396862e-082c-11e7-acf3-91257d9c9f2f	Duration: 771.06 ms	Billed Duration: 800 ms 	Memory Size: 1536 MB	Max Memory Used: 18 MB	
	1489437429147
`

**Comment by zeph** [comment]
@jicowan yes, I know the output...

 I said I have a separate patch for it if u wanna try getting the result HTTP codes

**Comment by jicowan** [comment]
@zeph Thanks.  I'd be willing to try to the patch.  If it's too big a hassle, I think I can get what I need from the ALB logs.

**Comment by zeph** [comment]
@jicowan I thought there was one, it shall be pretty simple to add a print to the statusCode once obtained by the client code here:
 - https://github.com/zeph/goad/blob/desenmerda-te/lambda/lambda.go#L284
