### ISSUE TITLE
No results received - IAM account with security policy applied

### ISSUE THREAD

**Issue by ripzay** [goadapp/goad#110]
Firstly: Running goad under my administrator IAM user which has a very unrestrictive policy applied works without issue

However we need to ensure that the IAM account we use for goad in production has a limited set of permissions, we've created an IAM user the following IAM policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "4b79821b",
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:GetRole",
                "iam:PutRolePolicy",
                "iam:PassRole"
            ],
            "Resource": [
                "arn:aws:iam::*:role/goad-lambda-role"
            ]
        },
        {
            "Sid": "bc2a9593",
            "Effect": "Allow",
            "Action": [
                "lambda:CreateFunction",
                "lambda:GetFunction",
                "lambda:CreateAlias",
                "lambda:GetAlias",
                "lambda:UpdateFunctionCode"
            ],
            "Resource": [
                "arn:aws:lambda:*:*:function:goad"
            ]
        },
        {
            "Sid": "2fa64ebc",
            "Effect": "Allow",
            "Action": [
                "sqs:*"
            ],
            "Resource": [
                "arn:aws:sqs:*:*:goad-*"
            ]
        }
    ]
}
```

When we run goad with the same parameters using the credentials of an account with this policy applied we are getting the 'No results received' message.

I'm unable to find in the documentation what permissions the iam user running goad needs in order to function, we've created this policy by trial and error, correcting after each error message, but the error messages stopped and now we're just left with 'No results received'; whether we have enough here and the problem is elsewhere we do not know.

Any help would be appreciated

**Comment by cwaltken-edrans** [comment]
You can find the applied policy in [infrastructure/infrastructure.go](https://github.com/goadapp/goad/blob/master/infrastructure/infrastructure.go).

**Comment by zeph** [comment]
@ripzay does that answer ur question?

**Comment by ripzay** [comment]
@zeph / @cwaltken-edrans - i believe the policy described in infrastructure/infrastructure.go applies to the lambda function which is being run, but not to the IAM user that is running the goad CLI locally, it's this account that we are trying to apply a policy to grant enough permissions to run goad.

I believe that the policy document described in my OP gives enough permissions to that IAM user to allow the goad CLI to create the required resources in AWS (the lambda function itself, the policy described in infrastructure.go etc), but is unable to receive results - i'm not sure whether this is because the lambda function isn't producing any results when the run is initiated using our IAM account with this policy document applied, or whether the IAM account has insufficient permissions to read the results back into the CLI.

Thanks for your time

**Comment by zeph** [comment]
@ripzay sorry, I really have a hard time to follow up on this... with a user with enough permissions to install the above IAM role, the lambda function will perform as by design... we are not describing the IAM role to be associated to ur user... patches/documentation/proposals are welcome

closing, feel free to reopen
