### ISSUE TITLE
Goad fails to build on macOS Sierra

### ISSUE THREAD

**Issue by benhorowitz** [goadapp/goad#111]
Make build fails with: fatal error: unexpected signal during runtime execution

Admittedly, I am not very familiar with Go, so please let me know if I should be looking elsewhere. 

➜  goad git:(master) make clean
rm -rf data/lambda/goad-lambda
rm -rf build
➜  goad git:(master) make osx
GOOS=linux GOARCH=amd64 go build -o data/lambda/goad-lambda ./lambda
\# encoding/xml
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x1ea99]

runtime stack:
runtime.throw(0x45ef80, 0x2a)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.(*gcWork).put(0xc820020720, 0xc820063d40)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/mgcwork.go:87 +0x49
runtime.greyobject(0xc820063d40, 0x0, 0x0, 0xc81fffce15, 0x0, 0xa06af0, 0xc820020720)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/mgcmark.go:956 +0x2f1
runtime.shade(0xc820063d40)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/mgcmark.go:894 +0x9a
runtime.gcmarkwb_m(0xc82048c978, 0xc820063d40)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/mbarrier.go:91 +0xc1
runtime.writebarrierptr_nostore1.func1()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/mbarrier.go:117 +0x134
runtime.systemstack(0xc820020a00)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:216 fp=0xc82009d6f0 sp=0xc82009d6e8
runtime.writebarrierptr_nostore1(0xc82048c978, 0xc820063d40)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/mbarrier.go:118 +0x71 fp=0xc82009d728 sp=0xc82009d6f0
runtime.writebarrierptr(0xc82048c978, 0xc820063d40)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/mbarrier.go:137 +0x4b fp=0xc82009d758 sp=0xc82009d728
runtime.hashGrow(0x38f160, 0xc82048c960)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/hashmap.go:769 +0x1b9 fp=0xc82009d788 sp=0xc82009d758
runtime.mapassign1(0x38f160, 0xc82048c960, 0xc82009e6c0, 0xc82009e248)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/hashmap.go:481 +0x55b fp=0xc82009d830 sp=0xc82009d788
cmd/compile/internal/gc.(*yyParserImpl).Parse(0xc820032048, 0xbb6728, 0x9a6260, 0x0)
	go.y:1203 +0xcaec fp=0xc8200a1ab0 sp=0xc82009d830
cmd/compile/internal/gc.yyparse()
	/usr/local/Cellar/go/1.5.1/libexec/src/cmd/compile/internal/gc/lex.go:1854 +0xb4 fp=0xc8200a1af0 sp=0xc8200a1ab0
cmd/compile/internal/gc.Main()
	/usr/local/Cellar/go/1.5.1/libexec/src/cmd/compile/internal/gc/lex.go:348 +0x1b6f fp=0xc8200a1df0 sp=0xc8200a1af0
cmd/compile/internal/amd64.Main()
	/usr/local/Cellar/go/1.5.1/libexec/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc8200a1e58 sp=0xc8200a1df0
main.main()
	/usr/local/Cellar/go/1.5.1/libexec/src/cmd/compile/main.go:26 +0x189 fp=0xc8200a1f30 sp=0xc8200a1e58
runtime.main()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc.go:111 +0x2b0 fp=0xc8200a1f80 sp=0xc8200a1f30
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200a1f88 sp=0xc8200a1f80
^Cmake: *** [lambda] Error 2

**Comment by gserra-olx** [comment]
are u trying to build from within `$GOPATH`, right? not an isolated code checkout
...I do also have golang 1.8.1 from homebrew, not 1.5.1 ... on an empty laptop:
```
$ history |tail -10
  513  go get github.com/tools/godep
(from ur repo checkout)  514  godep restore
  516  cd ..
  517  cd golang/src/github.com/
  518  go get github.com/goadapp/goad
  520  cd goadapp/goad/
  521  make
```

**Comment by zeph** [comment]
@benhorowitz build works like a charm from within the `$GOPATH`, please let us know if u still have issues
