### ISSUE TITLE
unit tests hang with no output

### ISSUE THREAD

**Issue by rawberg** [goadapp/goad#115]
Trying to get my dev environment up and running. When I run `go test` it starts executing, but never finishes and no output is shown on the console. 

I can successfully run `make` and build the binaries. I'm using Go version 1.5.2 on OSX. When I try using Go 1.6 I get `fatal error: MSpanList_Insert` errors. When I try Go version 1.7 I get `github.com/goadapp/goad	[no test files]`.

**Comment by zeph** [comment]
@rawberg I just merged on master several changes... did u try on that set of code?

**Comment by rawberg** [comment]
Yeah this is happening for me on master. What version of Go are you deving with? Readme says 1.5, travis.yml is 1.6 and the dockerfile for the web api is set to 1.8. 

For me 1.7 and 1.8.1 both output `github.com/goadapp/goad	[no test files]`.

**Comment by cwaltken-edrans** [comment]
That's correct there are currently very few unit tests on goad.
I recommend using 1.8 to execute the unit tests i wrote for the lambda package.
Hold tight! In the next few days I'll submit a pull request that also improves the `make test` recipe of the Makefile.

**Comment by cwaltken-edrans** [comment]
@rawberg : take a look at #121 and the travis build. You can see that unit tests are running fine.

**Comment by cwaltken-edrans** [comment]
I think we should close the issue.

**Comment by zeph** [comment]
closing, unless @rawberg says otherwise
