### ISSUE TITLE
goad not able to produce logs when run as a background nohup process

### ISSUE THREAD

**Issue by akhilesharora** [goadapp/goad#118]
I am trying to run goad at fixed intervals on an ec2 instance. When the nohup process is added to the background the logs/output json is not being generated. I am using the build from [issue#37](https://github.com/goadapp/goad/tree/issue%2337) 
```sh
nohup bash -c 'while sleep 300 ; do t=$(date +%Y%m%d%H%M%S); ~/goad -i -c 10000 -u  http://******.us-east-1.elb.amazonaws.com/event/dsfdsfdsf/fgfdgdfgdfg/abcdefg -n 200000 -o ~/logs/upstream/10k$t.log; done' &
```

**Comment by cwaltken-edrans** [comment]
Thanks for pointing it out as an issue. I noticed this as-well and it's definitely on the radar. PR of course welcome. :wink:

**Comment by akhilesharora** [comment]
I found a workaround to run it using **[screen](https://kb.iu.edu/d/acuy)** command in unix. Since **[screen](https://kb.iu.edu/d/acuy)** allows you to attach and detach from a terminal session, I ran the nohup script inside the screen session and then detached the user from that session returning back to the ec2 shell thus allowing the script running in the background.

**Comment by cwaltken-edrans** [comment]
That's a great workaround. Thanks for posting. :+1:

**Comment by zeph** [comment]
nice! thanks @akhilesharora
