### ISSUE TITLE
replace average times with percentiles 

### ISSUE THREAD

**Issue by aidylewis** [goadapp/goad#12]
Average response times can be misleading with high standard deviations, so I would suggest using either percentiles or mean with percentiles. I'd also add the max response time. 

[mean, 50, 95, 99, max]

**Comment by wendigo** [comment]
I can try to implement this @sdsykes

**Comment by wendigo** [comment]
Well, it won't be easy change as I would like to introduce hdr histogram both into lambda, queue and aggregations.

**Comment by aidylewis** [comment]
I'd probably forget mean: 

[min, 50%, 75%, 95%, 99%, Max]

**Comment by zeph** [comment]
@wendigo nice to see you too on this project ;) 
...cheers from OLX/NaspersClassifieds@Berlin

**Comment by zeph** [comment]
implemented & merged

**Comment by zeph** [comment]
@aidylewis please, have a try

**Comment by aidylewis** [comment]
@zeph Off work today, but will test tomorrow. Thanks.

**Comment by subwiz** [comment]
This is not in master? This commit seems to be available only in issue#37 branch.

**Comment by zeph** [comment]
@subwiz I merged https://github.com/goadapp/goad/pull/101 already... I don't get it
and issue#37 's branch is merged too https://github.com/goadapp/goad/pull/99 ...can u pinpoint me the commit u refer to? or make a pull request and I'll review it

**Comment by subwiz** [comment]
I was specifically looking for the `-i` parameter to compute the percentiles. That seems to be not available in the `master`?

**Comment by zeph** [comment]
it's not in the ab (apache benchmark) command line, so I'm asking our contractors to first baseline on that interface and add the extra features as part of a file based configuration (it will include a lot of other things) ...coming soon ;) [a month or two]

**Comment by subwiz** [comment]
Thanks @zeph! Till then we are building branch `issue#37` for the percentile computation.

**Comment by palmerabollo** [comment]
The [change that shows latencies in issue#37](https://github.com/goadapp/goad/commit/f08faa167411ff4429c60ae5ca83614ad4b94631) corresponds to goad 1.2.0. That version is already very different than master/2.x. It would be a pity to lose this change because averages are often misleading. Would it be possible to incorporate that change back into master?
