### ISSUE TITLE
go get github.com/gophergala2016/goad?

### ISSUE THREAD

**Issue by aidylewis** [goadapp/goad#13]
README.md

Does the repo in the go get command need to be:

```
go get github.com/goadapp/goad
```

And not:
```
go get github.com/gophergala2016/goad
``` 

?

**Comment by matiaskorhonen** [comment]
It does indeed (we forgot to change it when we moved the repo)

Fixed in 431bb0691fda7bd8a564fada601739ad59aa27e7, thanks.
