### ISSUE TITLE
infrastructure.go:46: undefined: Asset

### ISSUE THREAD

**Issue by vmogilev** [goadapp/goad#14]
go get is raising "undefined: Asset"

    ubuntu@dev01:~$ go get github.com/goadapp/goad
    # github.com/gophergala2016/goad/infrastructure
    /data/dev/golang/src/github.com/gophergala2016/goad/infrastructure/infrastructure.go:46: undefined: Asset

**Comment by vmogilev** [comment]
Workaround:

    cd $GOPATH/src/github.com/gophergala2016/goad
    make linux

**Comment by jcxplorer** [comment]
Not really a bug, but more of a limitation of our current build system, which requires the go-bindata tool to run before compiling. That unfortunately means that Goad is not go-gettable, which is not a big issue unless someone plans on using Goad as a library.

I'm very open to suggestions that don't include adding the generate bindata files to the repo, or arguments on why the bindata belongs in the repo. :grin:

Closing for now.
