### ISSUE TITLE
Current stable release version?

### ISSUE THREAD

**Issue by ilovezfs** [goadapp/goad#149]
Based on https://github.com/goadapp/goad/releases/latest it's not clear to me whether 1.4.1 or 2.0.0-rc2 is the current stable release version. Could you clarify which should be in Homebrew now? Thanks!

**Comment by zeph** [comment]
Hi @ilovezfs , we just tagged the `2.0.1`, please refer to that one. 

We are in the middle of a major refactoring of the way metrics are aggregated and computed, and it will be the `2.1` on which we will build the features of generic lambda libraries as executors.
Best,
@gserra-olx & @cwaltken-edrans

**Comment by ilovezfs** [comment]
@zeph cool, thanks. Mind marking that the latest release?

(Also, in the future, please use the "pre-release" checkbox for release candidates)

**Comment by zeph** [comment]
@ilovezfs yeah, the Travis-CI shall do it in a minute... 
I need to check the `pre-release` checkbox thing, I'm not aware about the process

**Comment by ilovezfs** [comment]
@zeph it's in the GUI but also part of the API https://developer.github.com/v3/repos/releases/

**Comment by gserra-olx** [comment]
thanks @ilovezfs for the tip, shall be fixed from now onwards

**Comment by ilovezfs** [comment]
@gserra-olx thank you!
