### ISSUE TITLE
version on CLI is wrongly reported

### ISSUE THREAD

**Issue by gserra-olx** [goadapp/goad#151]
I was expecting `2.0.1`

```
$ goad  -V
2.0.0-rc1x-bd9b62a2
```

**Comment by cwaltken-edrans** [comment]
Currently the version is composed like this VERSION-BUILD and to be configured in the makefile like this:

```
VERSION := 2.0.0-rc1x
BUILD := `git rev-parse HEAD`
```
I can check if we can capture the most recent tag on this version directly out of git.

**Comment by cwaltken-edrans** [comment]
I've modified the build script to auto-detect a the tag and use it as version string when building on travis.

**Comment by gserra-olx** [comment]
tnx @cwaltken-edrans
