### ISSUE TITLE
--output-json flag not working

### ISSUE THREAD

**Issue by ivanschwarz** [goadapp/goad#163]
Hey!
Thanks for all your work on this pretty neat tool! 
Just a quick report. [Readme](https://github.com/goadapp/goad/blob/master/README.md#cli) lists a flag `--output-json`, but [code](https://github.com/goadapp/goad/blob/7ad6dea2da6a284843cfbb578aed689dd313e3e7/cli/cli.go#L40) implements a corresponding functionality for a flag `--json-output`. I could've submit a PR, but I'm not sure, which one you want to stick with.

**Comment by gazcn007-tableau** [comment]
yea +1 on that, i think they meant --json-output
