### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by aaroncai-myob** [goadapp/goad#167]
Failed to build from source 
go get github.com/goadapp/goad

`github.com/goadapp/goad/infrastructure/docker
../../go/src/github.com/goadapp/goad/infrastructure/docker/docker.go:245: undefined: infrastructure.Asset
 github.com/goadapp/goad/infrastructure/aws
../../go/src/github.com/goadapp/goad/infrastructure/aws/aws.go:95: undefined: infrastructure.Asset`

**Comment by cwaltken-edrans** [comment]
This is a duplicate of #32.
Goad builds fine with `make build` or `make install`.
