### ISSUE TITLE
List of URLs and status codes?

### ISSUE THREAD

**Issue by bplus** [goadapp/goad#168]
Is it possible to see a list of retrieved URLs and status codes, like you can with siege?  

This assumes that goad parses retrieved web pages and follows them - if that's not the case, please let me know.

**Comment by cwaltken-edrans** [comment]
No, goad does not parse the pages and follows links.

We are working on a plugin architecture though. So it might soon be possible to run goad in the way you want.

The first plugin will be inspired by siege to allow the user to pass a file of URLs to goad to put load on different routes of a web application.
