### ISSUE TITLE
Docker Support Questions

### ISSUE THREAD

**Issue by rawberg** [goadapp/goad#172]
Experimenting with the docker integration via `--run-docker`. Looks like messages don't seem to be coming through from the containers into RabbitMQ. It gets into the Receive function without any errors but no messages come through the channel. Still learning the codebase and trying to understand how the docker pieces work together.

Is the message passing between the containers and RabbitMQ functional? What version of linux and docker has it be able to run on?

I tried Ubuntu Server 16.04, Go 1.8.1, Docker 17.09.0-ce.

**Comment by cwaltken-edrans** [comment]
Hi David,

sorry for my delayed reply. The docker feature is still considered experimental.
Could you try the latest release version? It's working fine on my machine.

The latest development version does have a bug with the docker-runner though. Thanks for letting me know. I'll let you know as soon as I came around to fix things.

**Comment by cwaltken-edrans** [comment]
I've found the error for the current master branch.

**Comment by rawberg** [comment]
Just tested your branch from #173 and confirmed it's working on my test setup - Ubuntu Server 16.04, Go 1.8.1, Docker 17.09.0-ce.

Thank you for the fix! I'll continue experimenting!

**Comment by cwaltken-edrans** [comment]
The docker mode still does not work in swarm mode with a remote machine holding the rabbitmq to gather the results.
That would definitely be a great feature.
