### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by thalesfsp** [goadapp/goad#178]
Hi,

 Tried to access the website, isn’t working :(

![cc3d7052-ebf2-4652-8404-ceea997426ed](https://user-images.githubusercontent.com/750360/35473428-623a3ec6-0335-11e8-99ba-530ca3d6a252.png)

**Comment by ilovezfs** [comment]
@cwaltken-edrans the website still seems to be down

**Comment by matiaskorhonen** [comment]
Sorry, there were some issues with the Cloudflare set-up. The site should come back up as soon as Cloudflare issues a new cert for it.

**Comment by thallbeck** [comment]
Similarly, the links for the Windows 64 and 32 bit downloads go to 404 pages.
https://github.com/gophergala2016/goad/releases/download/v1.3.0/goad-gopher-gala-windows-x86-64.zip
