### ISSUE TITLE
Guessing no longer supported?

### ISSUE THREAD

**Issue by michaelmano** [goadapp/goad#190]
Im getting the error `InvalidParameterValueException: The runtime parameter of nodejs is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs6.10) while creating or updating functions.`

Im just curious if this application works for anyone else.

**Comment by jvsteiner** [comment]
same here - is this project dead?

**Comment by jvsteiner** [comment]
@michaelmano - it's an easy fix if you still want to try it, I made a PR [from here](https://github.com/jvsteiner/goad/tree/node-version) if you are interested.

**Comment by matiaskorhonen** [comment]
Fixed by merging #191
