### ISSUE TITLE
Any plans to support OAuth?

### ISSUE THREAD

**Issue by timwilliate** [goadapp/goad#2]
This is a really neat tool. Do you have any plans to support testing OAuth secured URL's?

**Comment by sdsykes** [comment]
If that would just require adding the ability to define custom headers, then that would be a great feature to add.

But were you thinking of the whole OAuth process? How would you imaging using it?

**Comment by timwilliate** [comment]
Thank you for responding so quickly. I envision using this to load test REST endpoints that are secured with OAuth, as opposed to being completely pubic URL's. I think the ability to add custom headers would work fine for that task.

**Comment by jcxplorer** [comment]
Implemented by #9.
