### ISSUE TITLE
Attempting to test

### ISSUE THREAD

**Issue by sh4t** [goadapp/goad#21]
Trying to give this a whirl and getting IOWait issues on the routines

`
shat@bipolar:~$ ./goad -n 100 -c 10 -r us-east-1,us-west-2,eu-west-1,ap-northeast-1 -m PUT -u "http://myaddress.tld"

No results received
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x51efaf]

goroutine 1 [running]:
github.com/gophergala2016/goad/infrastructure.(*Infrastructure).createIAMLambdaRole(0xc820013a70, 0x9875a0, 0x10, 0x0, 0x0, 0x7f52e38d5aa8, 0xc82001c340)
	/Users/matt/Code/go/src/github.com/gophergala2016/goad/infrastructure/infrastructure.go:140 +0x55f
github.com/gophergala2016/goad/infrastructure.(*Infrastructure).setup(0xc820013a70, 0x0, 0x0)
	/Users/matt/Code/go/src/github.com/gophergala2016/goad/infrastructure/infrastructure.go:42 +0x57
github.com/gophergala2016/goad/infrastructure.New(0xc82001ca40, 0x4, 0x4, 0xc82006c510, 0xe7e500, 0x0, 0x0)
	/Users/matt/Code/go/src/github.com/gophergala2016/goad/infrastructure/infrastructure.go:25 +0x9d
github.com/gophergala2016/goad.(*Test).Start(0xc82002c070, 0x0)
	/Users/matt/Code/go/src/github.com/gophergala2016/goad/goad.go:62 +0x14b
main.start(0xc82002c070, 0xc820101e90, 0xc820018600)
	/Users/matt/Code/go/src/github.com/gophergala2016/goad/cli/cli.go:80 +0xea
main.main()
	/Users/matt/Code/go/src/github.com/gophergala2016/goad/cli/cli.go:65 +0x606

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0xa13a98, 0xc82002a728, 0x9300b8, 0x6, 0x42ff18, 0x2)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002a728, 0x0, 0x18)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002a728)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 7 [runnable]:
github.com/gophergala2016/goad/Godeps/_workspace/src/github.com/nsf/termbox-go.Init.func1()
	/Users/matt/Code/go/src/github.com/gophergala2016/goad/Godeps/_workspace/src/github.com/nsf/termbox-go/api.go:87 +0x40c
created by github.com/gophergala2016/goad/Godeps/_workspace/src/github.com/nsf/termbox-go.Init
	/Users/matt/Code/go/src/github.com/gophergala2016/goad/Godeps/_workspace/src/github.com/nsf/termbox-go/api.go:106 +0x8bd

goroutine 9 [IO wait]:
net.runtime_pollWait(0x7f52e38d6b90, 0x77, 0x453150)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820049fe0, 0x77, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitWrite(0xc820049fe0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:82 +0x36
net.(*netFD).connect(0xc820049f80, 0x0, 0x0, 0x7f52e38d5c68, 0xc82000f500, 0xece8f8c78, 0x26574034, 0xe7e3a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:114 +0x1f6
net.(*netFD).dial(0xc820049f80, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8240, 0xece8f8c78, 0x26574034, 0xe7e3a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/sock_posix.go:137 +0x351
net.socket(0x930568, 0x3, 0x2, 0x1, 0x0, 0xc8200f8200, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8240, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/sock_posix.go:89 +0x411
net.internetSocket(0x930568, 0x3, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8240, 0xece8f8c78, 0x5b26574034, 0xe7e3a0, 0x1, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/ipsock_posix.go:160 +0x141
net.dialTCP(0x930568, 0x3, 0x0, 0xc8200f8240, 0xece8f8c78, 0xc826574034, 0xe7e3a0, 0xc820011510, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/tcpsock_posix.go:171 +0x11e
net.dialSingle(0xc82007c380, 0x7f52e38d5b90, 0xc8200f8240, 0xece8f8c78, 0x26574034, 0xe7e3a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:364 +0x3f5
net.dialSerial.func1(0xece8f8c78, 0x26574034, 0xe7e3a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:336 +0x75
net.dial(0x930568, 0x3, 0x7f52e38d5b90, 0xc8200f8240, 0xc82003f6e8, 0xece8f8c78, 0x26574034, 0xe7e3a0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:40 +0x60
net.dialSerial(0xc82007c380, 0xc820011510, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:338 +0x760
net.(*Dialer).Dial(0xc82001a410, 0x930568, 0x3, 0xc82000f4c0, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:232 +0x50f
net.(*Dialer).Dial-fm(0x930568, 0x3, 0xc82000f4c0, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc82006c120, 0x930568, 0x3, 0xc82000f4c0, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:499 +0x79
net/http.(*Transport).dialConn(0xc82006c120, 0x0, 0xc82001cd40, 0x4, 0xc82000f4c0, 0x12, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:596 +0x19a9
net/http.(*Transport).getConn.func4(0xc82006c120, 0x0, 0xc82001cd40, 0x4, 0xc82000f4c0, 0x12, 0xc820018840)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:549 +0x66
created by net/http.(*Transport).getConn
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:551 +0x265

goroutine 11 [chan receive]:
net/http.(*Transport).getConn.func2.1(0xc820018840, 0xc82006c120, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:536 +0x4c
created by net/http.(*Transport).getConn.func2
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:542 +0x77

goroutine 12 [IO wait]:
net.runtime_pollWait(0x7f52e38d6ad0, 0x77, 0x453150)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82010e1b0, 0x77, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitWrite(0xc82010e1b0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:82 +0x36
net.(*netFD).connect(0xc82010e150, 0x0, 0x0, 0x7f52e38d5c68, 0xc82000f600, 0xece8f8c7d, 0x28d9ea98, 0xe7e3a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:114 +0x1f6
net.(*netFD).dial(0xc82010e150, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8330, 0xece8f8c7d, 0x28d9ea98, 0xe7e3a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/sock_posix.go:137 +0x351
net.socket(0x930568, 0x3, 0x2, 0x1, 0x0, 0xc8200f8300, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8330, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/sock_posix.go:89 +0x411
net.internetSocket(0x930568, 0x3, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8330, 0xece8f8c7d, 0xc828d9ea98, 0xe7e3a0, 0x1, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/ipsock_posix.go:160 +0x141
net.dialTCP(0x930568, 0x3, 0x0, 0xc8200f8330, 0xece8f8c7d, 0xc828d9ea98, 0xe7e3a0, 0xc820011650, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/tcpsock_posix.go:171 +0x11e
net.dialSingle(0xc82007c580, 0x7f52e38d5b90, 0xc8200f8330, 0xece8f8c7d, 0x28d9ea98, 0xe7e3a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:364 +0x3f5
net.dialSerial.func1(0xece8f8c7d, 0x28d9ea98, 0xe7e3a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:336 +0x75
net.dial(0x930568, 0x3, 0x7f52e38d5b90, 0xc8200f8330, 0xc8200c96e8, 0xece8f8c7d, 0x28d9ea98, 0xe7e3a0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:40 +0x60
net.dialSerial(0xc82007c580, 0xc820011650, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:338 +0x760
net.(*Dialer).Dial(0xc82001a410, 0x930568, 0x3, 0xc82000f5c0, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:232 +0x50f
net.(*Dialer).Dial-fm(0x930568, 0x3, 0xc82000f5c0, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc82006c120, 0x930568, 0x3, 0xc82000f5c0, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:499 +0x79
net/http.(*Transport).dialConn(0xc82006c120, 0x0, 0xc82001cd40, 0x4, 0xc82000f5c0, 0x12, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:596 +0x19a9
net/http.(*Transport).getConn.func4(0xc82006c120, 0x0, 0xc82001cd40, 0x4, 0xc82000f5c0, 0x12, 0xc820018b40)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:549 +0x66
created by net/http.(*Transport).getConn
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:551 +0x265

goroutine 14 [chan receive]:
net/http.(*Transport).getConn.func2.1(0xc820018b40, 0xc82006c120, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:536 +0x4c
created by net/http.(*Transport).getConn.func2
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:542 +0x77

goroutine 15 [IO wait]:
net.runtime_pollWait(0x7f52e38d6a10, 0x77, 0x453150)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82010e300, 0x77, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitWrite(0xc82010e300, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:82 +0x36
net.(*netFD).connect(0xc82010e2a0, 0x0, 0x0, 0x7f52e38d5c68, 0xc82000f6a0, 0xece8f8c82, 0x2fad0bc2, 0xe7e3a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:114 +0x1f6
net.(*netFD).dial(0xc82010e2a0, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8420, 0xece8f8c82, 0x2fad0bc2, 0xe7e3a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/sock_posix.go:137 +0x351
net.socket(0x930568, 0x3, 0x2, 0x1, 0x0, 0xc8200f8400, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8420, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/sock_posix.go:89 +0x411
net.internetSocket(0x930568, 0x3, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8420, 0xece8f8c82, 0xc82fad0bc2, 0xe7e3a0, 0x1, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/ipsock_posix.go:160 +0x141
net.dialTCP(0x930568, 0x3, 0x0, 0xc8200f8420, 0xece8f8c82, 0xc82fad0bc2, 0xe7e3a0, 0xc820011770, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/tcpsock_posix.go:171 +0x11e
net.dialSingle(0xc82007c600, 0x7f52e38d5b90, 0xc8200f8420, 0xece8f8c82, 0x2fad0bc2, 0xe7e3a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:364 +0x3f5
net.dialSerial.func1(0xece8f8c82, 0x2fad0bc2, 0xe7e3a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:336 +0x75
net.dial(0x930568, 0x3, 0x7f52e38d5b90, 0xc8200f8420, 0xc8200cb6e8, 0xece8f8c82, 0x2fad0bc2, 0xe7e3a0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:40 +0x60
net.dialSerial(0xc82007c600, 0xc820011770, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:338 +0x760
net.(*Dialer).Dial(0xc82001a410, 0x930568, 0x3, 0xc82000f660, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:232 +0x50f
net.(*Dialer).Dial-fm(0x930568, 0x3, 0xc82000f660, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc82006c120, 0x930568, 0x3, 0xc82000f660, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:499 +0x79
net/http.(*Transport).dialConn(0xc82006c120, 0x0, 0xc82001cd40, 0x4, 0xc82000f660, 0x12, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:596 +0x19a9
net/http.(*Transport).getConn.func4(0xc82006c120, 0x0, 0xc82001cd40, 0x4, 0xc82000f660, 0x12, 0xc820018de0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:549 +0x66
created by net/http.(*Transport).getConn
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:551 +0x265

goroutine 17 [chan receive]:
net/http.(*Transport).getConn.func2.1(0xc820018de0, 0xc82006c120, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:536 +0x4c
created by net/http.(*Transport).getConn.func2
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:542 +0x77

goroutine 18 [IO wait]:
net.runtime_pollWait(0x7f52e38d6950, 0x77, 0x453150)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82010e450, 0x77, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitWrite(0xc82010e450, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:82 +0x36
net.(*netFD).connect(0xc82010e3f0, 0x0, 0x0, 0x7f52e38d5c68, 0xc82000f720, 0xece8f8c87, 0x3ae90a8d, 0xe7e3a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:114 +0x1f6
net.(*netFD).dial(0xc82010e3f0, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8510, 0xece8f8c87, 0x3ae90a8d, 0xe7e3a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/sock_posix.go:137 +0x351
net.socket(0x930568, 0x3, 0x2, 0x1, 0x0, 0xc8200f8500, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8510, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/sock_posix.go:89 +0x411
net.internetSocket(0x930568, 0x3, 0x7f52e38d5c20, 0x0, 0x7f52e38d5c20, 0xc8200f8510, 0xece8f8c87, 0xc83ae90a8d, 0xe7e3a0, 0x1, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/ipsock_posix.go:160 +0x141
net.dialTCP(0x930568, 0x3, 0x0, 0xc8200f8510, 0xece8f8c87, 0xc83ae90a8d, 0xe7e3a0, 0xc820011890, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/tcpsock_posix.go:171 +0x11e
net.dialSingle(0xc82007c680, 0x7f52e38d5b90, 0xc8200f8510, 0xece8f8c87, 0x3ae90a8d, 0xe7e3a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:364 +0x3f5
net.dialSerial.func1(0xece8f8c87, 0x3ae90a8d, 0xe7e3a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:336 +0x75
net.dial(0x930568, 0x3, 0x7f52e38d5b90, 0xc8200f8510, 0xc8201256e8, 0xece8f8c87, 0x3ae90a8d, 0xe7e3a0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:40 +0x60
net.dialSerial(0xc82007c680, 0xc820011890, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:338 +0x760
net.(*Dialer).Dial(0xc82001a410, 0x930568, 0x3, 0xc82000f6e0, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/dial.go:232 +0x50f
net.(*Dialer).Dial-fm(0x930568, 0x3, 0xc82000f6e0, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc82006c120, 0x930568, 0x3, 0xc82000f6e0, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:499 +0x79
net/http.(*Transport).dialConn(0xc82006c120, 0x0, 0xc82001cd40, 0x4, 0xc82000f6e0, 0x12, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:596 +0x19a9
net/http.(*Transport).getConn.func4(0xc82006c120, 0x0, 0xc82001cd40, 0x4, 0xc82000f6e0, 0x12, 0xc820019080)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:549 +0x66
created by net/http.(*Transport).getConn
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:551 +0x265

goroutine 20 [runnable]:
net/http.(*Transport).getConn.func2.1(0xc820019080, 0xc82006c120, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:535
created by net/http.(*Transport).getConn.func2
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:542 +0x77
`

**Comment by sh4t** [comment]
beyond this, on osx I am seeing:

```
Press ctrl-c to interrupt2016/04/06 13:22:15 This operation, InvokeAsync, has been deprecated
             2016/04/06 13:22:15 This operation, InvokeAsync, has been deprecated
 2016/04/06 13:22:15 This operation, InvokeAsync, has been deprecated

```

Then No results received.  Any debugging?

**Comment by sdsykes** [comment]
Can you try with the latest version if you aren't using it? I made some new binaries a few days ago.

**Comment by sh4t** [comment]
I downloaded the newest osx and linux binaries and tested as well as compiled myself; receiving no results received on both.  I've checked IAM role permissions, lambda function, removed lambda function and re-added via binary, etc.. same result.

**Comment by sh4t** [comment]
The timestamp(s) on the lambda functions and SQS queue looks fine, created/modified matches up to execution timestamp.  I have tested on two AWS accounts, setup independently to attempt validation or probable cause related to IAM.  Any additional ideas appreciated.

**Comment by danielmotaleite** [comment]
@sh4t  for the "receiving no results received on both", get the git code and compile it... the last commit fixed a problem that fail to create the aws policy to allow goad to save the results in the SQS.

**Comment by sdsykes** [comment]
You may need to delete the IAM role so that a new one is created with the correct policy attached.
