### ISSUE TITLE
Update regions restriction

### ISSUE THREAD

**Issue by danielmotaleite** [goadapp/goad#23]
I was trying to use the eu-central-1 region, but i fails... looking to the code it is restricted to only this regions:

```
var supportedRegions = []string{
	"us-east-1",
	"us-west-2",
	"eu-west-1",
	"ap-northeast-1",
}
```
From http://docs.aws.amazon.com/general/latest/gr/rande.html we can see that eu-central-1 is a valid lambda region.

So i assume that this list is not updated, can you please update it?

Even better, add a flag to ignore this check, so this do not block any future AWS change and require a new release (or user recompile) to use any new region

**Comment by sdsykes** [comment]
OK, I'll add the new region for now.

**Comment by danielmotaleite** [comment]
There are now 2 more AP regions, so they should be added also
