### ISSUE TITLE
InvokeAsync deprecated

### ISSUE THREAD

**Issue by jazzl0ver** [goadapp/goad#25]
Hi and thanks for the awesome tool!

After building from latest sources and running, I get the following warning:
"This operation, InvokeAsync, has been deprecated"

Can you please fix it?

**Comment by jcxplorer** [comment]
Seems like there's a single Invoke operation now: http://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html

**Comment by zeph** [comment]
@jazzl0ver are u still getting it?

**Comment by jazzl0ver** [comment]
I haven't been using goad since then, sorry.
