### ISSUE TITLE
Nodejs version

### ISSUE THREAD

**Issue by jazzl0ver** [goadapp/goad#26]
AWS console displays
"We recommend selecting Node.js 4.3 as the runtime for functions written in Node.js." when opening the function

**Comment by whiteadam** [comment]
AWS recently announced support for Node 4.3 and Node 0.10 is approaching its EoL, so this is their standard prompt. In case you were worried about operability, I'm sure AWS will support Node 0.10 for a while more. That said, this code should do fine on 4.3 😄

**Comment by whiteadam** [comment]
Also, NodeJS is just executing a Go binary on the command line (wink wink)

**Comment by jazzl0ver** [comment]
Yeah, I've tested it against 4.3 as well. Since it works well, why not to change the default to 4.3 to avoid such annoying messages? :)

**Comment by whiteadam** [comment]
¯\_(ツ)_/¯

**Comment by zeph** [comment]
fixed https://github.com/goadapp/goad/pull/95

**Comment by zeph** [comment]
this has been already merged
