### ISSUE TITLE
Host Header not being passed

### ISSUE THREAD

**Issue by jbarratt** [goadapp/goad#29]
Often when load testing pre-production services behind an ELB it's nice to be able to send a fake host header through.  However, when goad is called with `-H "Host: foobar.com" http://some-elb.us-east-1.elb.amazonaws.com` the host header passed through to the hosts themselves is `some-elb.us-east-1.elb.amazonaws.com`. I verified that alternate headers were passed, e.g. `-H "GoadHeader: yup"` This makes it hard to use goad for pre-production hostname-sensitive workloads.

**Comment by jbarratt** [comment]
It appears this is a documented, oddly behaving issue. 

https://github.com/golang/go/issues/7682

For the Host header to be set, the request `Host` struct entry must be modified, as it is used as canonical when actually making the request.

**Comment by jcxplorer** [comment]
Fixed in #30.
