### ISSUE TITLE
AWS Credential Named Profile Support

### ISSUE THREAD

**Issue by ryanmaclean** [goadapp/goad#3]
As someone with many AWS accounts, it would be very cool if AWS credential profiles were supported for those with multiple environments. 

Here's the gist from the AWS docs: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles

What I'm imagining: 

`goad -p PERF_ENV -n 1000 -c 5 -u https://example.com`

*where PERF_ENV is defined in ~/.aws/credentials under the [PERF_ENV] heading, as opposed to [default]*

Note that the current work-around I'm using is to swap profiles using the[ awsenv-profiles](https://github.com/Raynes/awsenv-profiles) tool.

**Comment by jcxplorer** [comment]
I also have multiple AWS accounts so this was on my list of things to do during the hackathon. Unfortunately I didn't have the time to start it. 

This is definitely coming once we get write access to the repo again!
