### ISSUE TITLE
AWS named profiles are not working

### ISSUE THREAD

**Issue by mkubenka** [goadapp/goad#34]
Support for AWS named profiles is broken and not working.

Example command:
```
goad -p development -r eu-west-1 -n 1000 -c 20 -u http://google.com
```

Fail with following error:
```
AccessDeniedException: Cross-account pass role is not allowed.
```

**Comment by jbhennin** [comment]
I no longer see the support for names profiles.  Am I missing something?  -p is returning as an unknown short flag
