### ISSUE TITLE
Support for dynamic payloads?

### ISSUE THREAD

**Issue by christopherhein** [goadapp/goad#36]
Do you have any plans of making or being able to provide dynamic payloads or random tokenizing? I've gotten it partially by parsing the payload and tokenizing using `%random%` with -> `requestBody := strings.Replace(requestBody, "%random%", uuid.NewV4().String(), -1)` it "works" but only at the concurrency level which you supply this if you make a request using `-c 500 -n 10000` 500 would be unique and the other 9500 would be duplicates of that. 

Any help would be appreciated …

**Comment by danielmotaleite** [comment]
i agree that this might be useful to test systems with cache and without, to try to find bottlenecks in the system and how the autoscale might respond (if any)

**Comment by zeph** [comment]
I'm working on it*, feel free to add comments to my repo
 - https://github.com/zeph/goad/projects/1 

* I'm aiming to extend goad to support INI-file described test flow scenarios

**Comment by tomj** [comment]
maybe to start if we could just provide an array of URL's in which we've performed the randomisation ourselves?  ps: thanks for a great project 😄  🎉

**Comment by zeph** [comment]
@tomj  already implemented... 
 - https://github.com/zeph/goad/tree/single_huge_list
I actually need to refine it... but feel free to play with it
...basically right now it requires that at compilation time 
you give all the data in the data/desenmerda-te folder... 

on my master branch I'm instead focusing on keeping the binary as is
and instead do a copyOnWrite to the internal lambda zip file...

**Comment by zeph** [comment]
@all this is being implemented as generic integration of javascript based executors like siege, postman (we are focusing on those) ... I'd love your feedback from you guys. This is part of goad 2.x releases

details on implementation -> @cwaltken-edrans

**Comment by genexp** [comment]
hey @zeph FWIW - this is a really great approach.  Did it end up happening?  Doesn't look like its in 2.0

**Comment by zeph** [comment]
Hi @genexp , we area already in the 2.x versioning as we had some major code refactoring in preparation of the "abstracted executor approach". I'm on sick leave at the moment but @cwaltken-edrans can give you some further details about it. Best, GMS

**Comment by genexp** [comment]
Hey @zeph cool dude!  Yeah, the postman thing seems kinda janky, but in practice its kind of neat.  Outside of scenario support, there's a GUI for creating them, and they can be genarate from swagger and such too.  We've found its a nice way to share integration tests between engineering and separate QA team who probably isn't familiar with whatever language specific tool the engineering team happens to be using.

(It's much better than something like cucumber <cough> which sucks.)
