### ISSUE TITLE
Clarification: Overall

### ISSUE THREAD

**Issue by technion** [goadapp/goad#5]
Hi,

Many thanks for this tool - I'm finding it very effective.

In the default configuration, I note it appears to run across four different regions, simultaneously. It then presents "overall" statistics.

The "avgreq/s" appears to be an average across the avgreq/s from each region, however, this appears to be a confusing statistic, as the "average requests served by the target server" would be the sum of these values.

Are you able to confirm, or advise if I have read this wrong?

**Comment by sdsykes** [comment]
Yes, we too realised that we didn't get this calculation correct after the event, it's a bug. It's showing you the average across every region as you guessed, and not the more useful average at the destination server. It will be changed to the sum as soon as the voting is over and we can migrate the repo to a proper home.
