### ISSUE TITLE
Sustaining request during specific seconds.

### ISSUE THREAD

**Issue by jeyraof** [goadapp/goad#93]
Can i sustain sending request to destination during specific seconds?

When i do test performance like cpu usage, I need to sustain request sending.

**Comment by zeph** [comment]
@jeyraof we are coming to that, as soon as we release 2.0.0 we'll add these kind of features

**Comment by cwaltken-edrans** [comment]
I think we already have this. You can set the count of requests to execute to 0 and specify a time limit to run the tests.

**Comment by zeph** [comment]
@cwaltken-edrans we do, but it is affected by this issue... https://github.com/goadapp/goad/issues/142

closing this one
