### ISSUE TITLE
Switch to eawsy/aws-lambda-go-shim

### ISSUE THREAD

**Issue by lsuss** [goadapp/goad#94]
Hi, i'm a contributor of [eawsy/aws-lambda-go-shim](https://github.com/eawsy/aws-lambda-go-shim) and I would like to submit the idea to switch from your nodejs shim to a full go supported shim based on python lambda.
It's a lot more stable (due to fine grained error handling) and a faster/cleaner way to build lambda in go.

We would be happy to provide support through our gitter or whatever you prefer :).

**Comment by zeph** [comment]
@lsuss sorry, the implementation right now is pretty clean, the nodejs is triggering a native linux binary... nothing else... maybe in the future I'd include Postman/Foreman tests based on the npm package 

switching to python is not realistic as of now, we are investing (and already invested) a lot on golang
