### ISSUE TITLE
Freeze after starting

### ISSUE THREAD

**Issue by helper2424** [goadapp/goad#96]
Hello, I have problem with goad application. I have created new amazon account, setuped IAM user and builded last version of goad.  I am trying to run goad and it's freeze.

`goad -u http://srelease.hgstudio.ru`

http://take.ms/XhgOK - here what I see

Environment data: 
 goad version 1.2.0
 go version 1.7.3 darwin/amd64
 macos 10.12.2 (16C67)

Can anybody help? I wanna debug goad application, but doesn't know where is start. Thanks for help and sorry for stupid question.

**Comment by runners-takehara** [comment]
Same problem happens my environment and resolve with https://github.com/goadapp/goad/pull/95 .

**Comment by helper2424** [comment]
Thanks that really help. I think that core team should approve Guido PR

**Comment by helper2424** [comment]
So, 95 issue merged I close this issue
