### ISSUE TITLE
goad.io website domain expired

### ISSUE THREAD

**Issue by felipeamarante** [goadapp/goad#97]
Hey dudes fyi, http://goad.io is unreachable. 

The domain has expired.

https://www.nic.io/go/whois/goad.io

**Comment by zeph** [comment]
@jcxplorer I can propose my org to take it over if u want. 
GOAD will be a fully sponsored dev project in the organization in the next 3 fiscal quarters.

**Comment by felipeamarante** [comment]
back online 8) 

https://www.nic.io/go/whois/goad.io
